### ISSUE TITLE
Duplication of entity models

### ISSUE THREAD

**Issue by vrnRaptor** [Laike-Endaril/Dynamic-Stealth#105]
Left a petrified monster (ice and fire), right an armor stand (bibliocraft).
With Dynamic-Stealth
![2020-08-01_16 07 33](https://user-images.githubusercontent.com/13599993/89103243-00264380-d419-11ea-9748-a7bb137296b5.png)
Without Dynamic-Stealth
![2020-08-01_16 08 46](https://user-images.githubusercontent.com/13599993/89103328-a5411c00-d419-11ea-8291-68c18589f9dd.png)

**Comment by Laike-Endaril** [comment]
Have you tried applying the full bypass filter?

After running the modpack, go to config/fantasticlib/reference/entities.txt, and look for likely entity names.

Then in the DS config, add those to the entity-specific full bypass list.  In most special cases like these, this should fix any issues.

**Comment by Laike-Endaril** [comment]
Looks like the biblio armor stand has already been fixed in my indev version of DS (not sure if that fix is in latest release yet or not).

Ice and fire has a "statue" entity, but doesn't seem to use it for petrified entities, so my previous suggestion will not help.  It uses the original entity and does some strange hackery.  It doesn't use a potion effect, and it doesn't add any AI tasks.

I'll see if I can detect it via render layers, but if not, then I'll likely not bother with it anymore for now.

**Comment by Laike-Endaril** [comment]
This should be fixed in the latest release (104)
