### ISSUE TITLE
Suggestion:undead will avoid the fire

### ISSUE THREAD

**Issue by MokoBlack** [Laike-Endaril/Dynamic-Stealth#37]
This is inspired by the fact that human ancestors used fire to expel wild animals. This feature encourages players to use limited torches or burning hellstone reasonably to build safe areas at night.

I m probably use more hardcore torch with it ,if this feature can be done（torch will go out）

**Comment by Laike-Endaril** [comment]
Hmm...this might be a bit outside the idea of "dynamic stealth", but I'll think about it anyway.  When I get back into the AI side sometime I may add it.

For the hardcore torches, maybe check out this existing mod: [https://minecraft.curseforge.com/projects/survivalist-lighting?gameCategorySlug=mc-mods&projectID=245884](https://minecraft.curseforge.com/projects/survivalist-lighting?gameCategorySlug=mc-mods&projectID=245884)

**Comment by MokoBlack** [comment]
Yes  i agree too . maybe create a new mod

**Comment by Laike-Endaril** [comment]
Btw, when you say "avoid fire" do you just mean they would avoid walking through fire?  Or do you mean they would avoid fire from some distance?  In vanilla they will literally walk directly through fire blocks.

**Comment by MokoBlack** [comment]
Should  be stay away

**Comment by MokoBlack** [comment]
Like what human ancestors do

**Comment by Laike-Endaril** [comment]
Alright...how about other light sources?  Should they avoid light in general, or only avoid fire?

Reason I ask is because it would probably be easier to make them avoid certain light levels than to make them avoid certain blocks from a certain distance

(and if they avoid light levels above a certain amount it automatically translates to avoiding fire, since fire emits light)

Handheld torches would be a separate thing either way, if that was wanted

**Comment by MokoBlack** [comment]
Just fire i think .. because i m using it with other mod that make undead more undead like , and the fire make them more weaker. so if their afraid fire ,it will get more immersive

**Comment by Laike-Endaril** [comment]
Alright, closing this since it would be a new mod and not a DS thing.  I don't know for sure if/when I'll get to it though.
