### ISSUE TITLE
Error since version 067

### ISSUE THREAD

**Issue by Finelarme9** [Laike-Endaril/Dynamic-Stealth#44]
Hey there
Since the last version (DynamicStealth-1.12.2.067.jar) I get this error log (spam) (https://pastebin.com/raw/BCzTe9XG). There is no server crash yet. Do you need more information ?
NB: It seems to be a repitition of a same error type ?

**Comment by Laike-Endaril** [comment]
`Caused by: java.lang.NullPointerException
at thexfactor117.lsc.events.EventPlayerStartTracking.onPlayerStartTracking(EventPlayerStartTracking.java:55) ~[EventPlayerStartTracking.class:?]`


This NPE is what's causing the log spam.  If the code for Loot Slash Conquer hasn't changed, then it would be coming from...

https://github.com/TheXFactor117/Loot-Slash-Conquer/blob/692d8eeb4debf48be7be6dc9718740279e160ef1/src/main/java/thexfactor117/lsc/events/EventPlayerStartTracking.java#L55

And if that's true, then "chunkLevelCap" is null.  I haven't a clue why, though, as I'm pretty sure it has nothing to do with DS.  I loaded up a game with DS 067 and the latest version of LSC and flew around for a while, but did not encounter the error.

To be thorough, can you load the world you're getting the error on using DS 066, and see if it still throws errors?

If it does, then also try this:
1. Make a copy of the world which is getting the errors
2. Load the copy without DS installed at all (it will show a warning, go ahead and load; this is why you have a copy)
3. See if it still has errors

I have at least one more idea, but I'd like to know what happens in these 2 situations first if possible

**Comment by Finelarme9** [comment]
Thank you a lot for your support. I'm gonna make these tests today. The problem maybe comes from Loot Slash Conquer yes. I will give you some feedback fast.
**Edit: I come back to you fast. I am very busy with work.**

**Comment by Laike-Endaril** [comment]
I'm closing this one for now due to inactivity, but if you come across it again feel free to open a new issue referencing this one.

You could also post here and I could reopen it, but there's a chance I could miss the notification and not see your post.
