### ISSUE TITLE
[SUGGESTION] Stealth gauge ignore list

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#48]
Can you make a special config for adding mobs NOT affecting stealth gauge (the "eye" thing).
For example i want to make so creeper does not affect "eye", and can creep up to player undetected.
Maybe you can somehow combine it with list of mobs can see you everywhere, and can pathfind to you even from far away. It would work great with creepers, hue hue.

**Comment by Laike-Endaril** [comment]
Sounds fine, but I'm taking a break from modding for now.  I'll leave this open for when I come back.


If you want a mob to be able to see you anywhere, you can give them natural soul sight.  Natural soul sight is in (server settings -> senses -> sight -> entity specific settings)

With DS, any mob can approach from far away (in fact, from any distance, no matter how far), so long as they can see you, so giving a mob soul sight will also allow them to approach you from any distance.

I may need to put a limiter on distance for soul sight...because I believe right now, if 2 players are in the overworld a thousand blocks from each other, any hostile monster with soul sight near player A could theoretically target player B and vice versa.  One more thing for the TODO list I suppose

**Comment by Laike-Endaril** [comment]
This feature is now implemented in the most recent release (1.12.2.073)!
