### ISSUE TITLE
Render Issues w/ Millenaire

### ISSUE THREAD

**Issue by WenXin20** [Laike-Endaril/Dynamic-Stealth#50]
Forge v14.23.5.2838
Dynamic Stealth v1.12.2.073
Millenaire v7.2.0

Whenever I focus on a villager from Millenaire, the outline renders as black instead of colored, which also makes it a little hard to read the name tag. Just a minor bug otherwise.
![2019-06-02_12 59 29](https://user-images.githubusercontent.com/12000593/58850393-eb52f200-8653-11e9-99c4-981537962e9c.png)

**Comment by Laike-Endaril** [comment]
I ran into this issue myself, but IIRC it was not a bug with DS x Millenaire, but rather a but with Millenaire x Vanilla (specifically, any glow effect triggered this issue, I believe).  I'll double check, but if this is the case, then it's purely a Millenaire thing, and I can't reasonably fix it from my end.

**Comment by Laike-Endaril** [comment]
Yes, this still happens when running Millenaire *only*, no other mods involved.  Just find a Millenaire villager and shoot it with a spectra arrow to see the same effect.  DS is just leveraging the vanilla glow effect for highlighting entities.

The exception is the color of the glow effect (ie. the black outline; this part is not a glitch).  It's a black-colored glow effect from DS, marking the entity as a "threat-bypass" entity (does not use DS AI or threat system).  Millenaire villagers are in threat bypass mode by default in order to avoid some compat issues with AI (mostly pathfinding and physics)

There are a couple workarounds you can use from DS if you want, but both have side-effects which you may or may not care about, and neither will help if a Millenaire villager gets glow from something else, or if you get the soul sight potion effect:

1. Disable glow effect for currently targeted entity.  This will ofc disable the glow effect on the currently targeted entity *for all entities*, ie. you will not have a glow effect for the DS targeting system at all
(client settings -> hud -> targeting hud style -> glow)

2. Disable targeting of threat bypass entities.  This will completely disable the targeting HUD for *all* threat bypass entities, including but not limited to the ender dragon and slimes
(client settings -> hud -> targeting filter -> bypass)

I'll open an issue on the Millenaire tracker for this and link it here shortly

**Comment by Laike-Endaril** [comment]
Here is the issue on their tracker, if you're interested:
https://gitlab.com/Millenaire/Public/issues/475

**Comment by WenXin20** [comment]
Ok, thanks for looking into it!
