### ISSUE TITLE
crash to desktop after being killed from behind by zombie

### ISSUE THREAD

**Issue by supremedutchgamer** [Laike-Endaril/Dynamic-Stealth#55]
https://paste.ee/p/zwmpW < log

i dont know exactly what caused this crash. but from the crash reports it looks to be a dynamic stealth thing?

**Comment by Laike-Endaril** [comment]
Yes, and I *think* I've found it (technically in Fantastic Lib if I was right).  This should be fixed in the next versions of DS/FL when I release them.

In the meantime, if you happen to have an empty string entry in one of the interaction settings, removing it may fix the crash.  Not sure if you do, but that would probably do such a thing as it is right now in version 079.

**Comment by Laike-Endaril** [comment]
Alright, this *should* be fixed in the latest release (1.12.2.080).  If not, just post here and I'll reopen the issue.
