### ISSUE TITLE
Minecolonies Barbarian AI Issues

### ISSUE THREAD

**Issue by WenXin20** [Laike-Endaril/Dynamic-Stealth#62]
Minecraft v1.12.2
Forge v14.23.5.2838
Dynamic Stealth v1.12.2.082
Minecolonies v0.10.307-Alpha

I suspect the might be a mod compat issue with Minecolonies' Barbarians. Minecolonies spawn in Barbarians to raid the colony and attack. It spawns them away from the colony and the barbarians head towards the colony (coordinates of where they spawned are in the log) but I noticed with my modpack that the Barbarians just stand around and don't head towards the colony. They only start to move once the player is in range to attack me.

**Comment by Laike-Endaril** [comment]
Hmm, they might require the ability to "see" the colony, which would make that happen...

I'll add it to my list

**Comment by WenXin20** [comment]
Thanks. I also forgot to mention that Minecolonies also adds pirates, so that mob might have the same issue too.

**Comment by Laike-Endaril** [comment]
Have looked into this a few times but have not found the root of the issue yet

**Comment by WenXin20** [comment]
Maybe check with the Minecolonies Developers?

**Comment by Laike-Endaril** [comment]
Yep, doing that now, hopefully they can help identify the issue

**Comment by Laike-Endaril** [comment]
Alright, they helped me get the right testing environment set up (I wasn't familiar with requirements for raids to happen).  I tested with just Minecolonies first and observed barbarian behavior...

...and then I tested with Dynamic Stealth installed, and they still worked fine!  Still approached my settlement, paused, then started searching random huts.

I'm thinking you might be getting a compat issue from another mod, or in the worst case, possibly a 3+ way compat issue between Minecolonies, DS, and at least one more mod, all put together.

When you have the time, if you can run a test with only Minecolonies and DS installed (and their requirements), that would be great.

The version of DS you're using is fine; there have been no AI changes since then that would have any effect on this.  For my tests, I was using the default configs for all mods.

**Comment by WenXin20** [comment]
Interesting, I'll let you know when I get around to testing it. Thanks!

**Comment by Laike-Endaril** [comment]
Note: if the raiders happen to collide with each other, they might stop and stare at each other.
If that happens and they don't go back to raiding, you might need to disable their sense of feel
(server settings -> senses -> touch)

Closing this one for now, but can reopen if more info comes in (just respond here if so)

**Comment by WenXin20** [comment]
I haven't gotten around to more testing, but I have noticed that when raids occur, the barbarians are spawned in the exact same spot. They don't seem to move from that spot unless I hit them to cause knockback. I'll try disabling the Sense of Feel next time they spawn in.

**Comment by Laike-Endaril** [comment]
Alrighty, but make sure sense of feel is disabled *before* they spawn in ;)

**Comment by Laike-Endaril** [comment]
I've improved the touch sense logic in the latest release, so it should no longer interfere with things like this.  I have a feeling this is what was causing an issue.

Grab the latest version (089) when you get a chance, and hopefully you won't run into this again.  I *think* this one is officially closed now, but if not, feel free to respond here again ofc
