### ISSUE TITLE
Render issues with Optifine + BSL Shaders

### ISSUE THREAD

**Issue by Clyybber** [Laike-Endaril/Dynamic-Stealth#80]
Looks like depth-buffer/transparency issues?
Screenshots:
https://imgur.com/a/C0WmsqO

**Comment by Clyybber** [comment]
I've seen this kind of issue with transparency and shaders before, with leaves particles from coro's weather mod.
I guess a workaround/solution would be to add an option to disable entity fading completely, as even with the parameters set to the values where it shouldn't matter, the issue is still present.

**Comment by Clyybber** [comment]
ping @Laike-Endaril just in case you missed this, or need help reproducing

**Comment by Laike-Endaril** [comment]
Github doesn't have a normal way to get notifications for new issues on your own repos, unfortunately (pet peeve)...so I hadn't seen this post yet.

Looking back at the code for entity fading now, I can see a couple possible issues with shaders.  I'll look into it

**Comment by Clyybber** [comment]
Oh, I think it does, you have to watch the repo (right next to the star and fork buttons)

Thanks for looking into it :)

**Comment by Laike-Endaril** [comment]
For some reason I thought I had tried that already, but maybe not?  In any case, trying it :P
Maybe it was just that it didn't have a way to do so globally, for all owned repos...idk

Anyway, duplicated the issue.  Trying to decide if I can make the fading itself actually compatible or not (ie. display in an expected manner, even with fading + shaders)

**Comment by Laike-Endaril** [comment]
Found the main issue you're probably having; either optifine or this shaderpack (did not test which) is incompatible with the vanilla glow effect (in addition to entity fading).  Possibly one of the reasons they have their own glow effect...but for some reason theirs is not triggering correctly.  I'm guessing they based it on the potion effect instead of the boolean check...

Anyway, by default, DS uses a glow effect on your currently focused target.  Disabling this (along with entity fading) fixes the issue for me while using the shader.

You can disable this in
(client settings -> HUD -> targeting HUD style -> glow)

Almost 100% sure this will fix your issue, but if not, tell me and I'll reopen

**Comment by Laike-Endaril** [comment]
(Side note: no, I cannot actually make the fading compatible from my end.  It would have to be supported from the shader side to work correctly with it enabled)
