### ISSUE TITLE
[Crash] with JED, presumably

### ISSUE THREAD

**Issue by TekSoda** [Laike-Endaril/Dynamic-Stealth#82]
Dynamic Stealth seems to cause crashes when I fly around in a dimension made with Just Enough Dimensions, and it seems to always relate to Villagers being ticked.

I dont plan on keeping villagers in the pack at all, so it's not anything urgent, but I felt I probably should report this.

https://pastebin.com/GSibXxcW

**Comment by TekSoda** [comment]
this may be a separate crash (as it involved no dimensions or villagers), or the same one, and triggered immediately after world creation.

https://pastebin.com/3mjMaf9f

edit: they're probably related, actually, as this world used the Just Enough Dimensions overworld world provider. I usually use dooglamoo, but forgot to set it this time. On creating yet _another_ test world with the dooglamoo world type, there was no crash.

edit 2: aaaand one last crash log _in_ dooglamoo but _with_ villagers. now im just extremely confused.

https://pastebin.com/gE2hF95s

**Comment by kappa-maintainer** [comment]
I got a similar crash, but without JED and dooglamoo: https://pastebin.com/6mtiANWn

The problem may relate to endless raytracing, because these lines appear in the log:

[10:35:02] [Server thread/INFO] [STDERR]: [com.fantasticsource.mctools.ImprovedRayTracing:rayTraceBlocks:243]: WARNING: ENDLESS RAYTRACING DETECTED!  This warning will not show more than once every 5 seconds, but may be happening far more often
[10:35:02] [Server thread/INFO] [STDERR]: [com.fantasticsource.mctools.ImprovedRayTracing:rayTraceBlocks:244]: From (295.5, 62.065858841893395, -995.5) to (295.0, 62.2331431785803, -991.0)

**Comment by Laike-Endaril** [comment]
The 1st, 2nd, and 4th are related to each other

The 3rd seems to be missing a stacktrace?  That's odd...

I'll look into the ones with traces in them

**Comment by Laike-Endaril** [comment]
Oh, and this is very likely not directly related to JED...at least for the 3 with stacktraces.  I have no idea what the cause was for the crash in the 3rd link, but it's likely not related to the others at all

**Comment by Laike-Endaril** [comment]
Just in case, if you both know what configs you had for DS at the time, that may help as well

@Varg95 Same; if any/all of you can tell me whether you were using default DS configs, or if not, send me your DS config files, it will let me narrow some things down a bit

**Comment by TekSoda** [comment]
[dynamicstealthconfigs.zip](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3914178/dynamicstealthconfigs.zip)

I was not using default configuration settings, and my folder contained two configs from separate updates.

**Comment by kappa-maintainer** [comment]
I have deleted the config folder before the crash, so I believe DS is using the default config.

**Comment by Laike-Endaril** [comment]
Thanks both

I was unable to replicate so far, but based on the code logic, I have a likely fix in the works and will release an update sometime today or tomorrow.  I'll mention it here when it's uploaded.

**Comment by Laike-Endaril** [comment]
An update for Fantastic Lib is now available which should hopefully fix this issue (version 028).

An update for Dynamic Stealth is also available, but if you're still on version 095 then you're not missing anything except the higher Fantastic Lib version requirement (in order to enforce the fix in the library)

If any/all of you can test it out for me and tell me whether you continue to see crashes or not, that would be great, since I haven't reproduced the issue locally.  Please post any new crash logs if you still get crashes, in case the cause is different from before

@Varg95 Just making sure you see this as well

**Comment by kappa-maintainer** [comment]
Seems not working, got a crash report: https://pastebin.com/vaPPKh7T
The minecraft log shows similar lines before the crash:

[11:43:25] [Server thread/INFO] [STDERR]: [com.fantasticsource.mctools.ImprovedRayTracing:rayTraceBlocks:243]: WARNING: BEYOND-LIMIT RAYTRACING DETECTED!  This warning will not show more than once every 5 seconds, but may be happening far more often
[11:43:25] [Server thread/INFO] [STDERR]: [com.fantasticsource.mctools.ImprovedRayTracing:rayTraceBlocks:244]: From (-112.5, 65.62000000476837, 66.5) to (-122.0, 67.34999999403954, 82.0) (distance: 18.26178741455078)
[11:43:25] [Server thread/INFO] [STDERR]: [com.fantasticsource.mctools.ImprovedRayTracing:rayTraceBlocks:245]: Limit: 200 iterations (not based directly on distance, but longer distances are generally more iterations)

**Comment by Laike-Endaril** [comment]
I've built a debug version of the library, which may produce some useful data for me to look at

If you can get the crash with this version, there should be a list of positions in the log file (probably not in the crash report).  If I can see the data starting from the WARNING: BEYOND-LIMIT and ending at the end of the positions list, I may be able to figure something out

[FantasticLib-1.12.2.028b.zip](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3914710/FantasticLib-1.12.2.028b.zip)

I'll keep looking over the code in the meantime

**Comment by Laike-Endaril** [comment]
To be more precise, I already have a solution which should prevent the crash...but based on the errors you're getting, the raytrace itself may not be pathing correctly somehow, so this debug version artificially enables the crash again and outputs additional data (all block positions iterated for the raytrace)

**Comment by kappa-maintainer** [comment]
https://pastebin.com/fpK0jmMM

**Comment by Laike-Endaril** [comment]
Thanks, looks like my hunch was right; the algorithm is passing by the side of the "ending block position" instead of through it, causing the raytrace to run for the maximum number of iterations before ending (200 block checks).

...I'll keep looking into this

**Comment by Laike-Endaril** [comment]
Aha, I finally reproduced this by forcing a raytrace using the exact start and end points from your data.  It must be a pretty rare occurrence in general, but once it happens, that same raytrace will likely run as soon as you load the world again (unless it was in an area where no players are logged in any longer)

In any case, I finally have a way to properly debug it, and can officially say that it's not related to other mods and is strictly an issue with my raytrace algorithm

**Comment by Laike-Endaril** [comment]
Alright, the newest Fantastic Lib (029) + Dynamic Stealth (097) have a fix for the root cause of the issue, which I was finally able to identify.  This error basically required perfect alignment of the stars...which is why not many people encountered it.  Feel free to ask if you want the details.

@Varg95 Last ping from me, just making sure you see this message ^

@TekSoda I have no idea what the crash in the 3rd link, but it's not related to the rest of them, and is very likely not related to any of my mods.  It's more likely related to either a coremod, java itself, your OS, firmware, or hardware, seeing as how it didn't even print out a proper stacktrace

**Comment by Laike-Endaril** [comment]
And of course, even though I'm 99% sure this is fixed, feel free to post here if you encounter it again and I'll reopen this

**Comment by kappa-maintainer** [comment]
The latest build of FantasticLib solved the problem.

**Comment by Laike-Endaril** [comment]
:+1:
