### ISSUE TITLE
Clearing current attack target from AI does not update visual display

### ISSUE THREAD

**Issue by Jackiecrazy** [Laike-Endaril/Dynamic-Stealth#84]
If a mod would set the attack target of a mob to null, the HUD does not update accordingly, and would still show "attacking [mob]".
This mostly pertains to EBWizardry's smoke bomb and mind trick. On another note, does muffle work with DS? I can't quite tell.

**Comment by Laike-Endaril** [comment]
DS has its own threat system, which alters the way target handling is done.  Basically, if it has threat toward a certain target, it will retain that target in memory until threat runs out (even if the attack target is set to null).  It will once again attempt to find and attack that specific target when it's able to again.

In order to completely lose/change target, a mod would need to call one of the DS methods to set its threat target and/or level (amount).

I've played EB Wizardry, but it's been a long time...IIRC smoke bomb basically immobilizes them, right?  Probably blocks AI from running for the duration, I think?

Mind trick was a spell which made them fight for you for the duration, right?

And I can't remember what muffle does...

Maybe refresh my memory on those spell effects

Also, what happens when something with a threat level is hit by mind trick?  Like, what does the mob actually do?  Does it...
...still attack you?
...attack your enemies?
...do nothing?
...go into search mode? (move and spin)

**Comment by Jackiecrazy** [comment]
The mob just does nothing. While the spell functions normally, the HUD still shows that it's attacking, which throws me off slightly. Mind trick and smoke bomb continuously reset the attack target, while muffle suppresses all player sounds for its duration.

**Comment by Laike-Endaril** [comment]
DS still doesn't have sound-based detection yet, so muffle will effectively act as it would with vanilla, I believe.  The only exception is that mobs do use their "hearing" for warning *each other*, but that's not a sound made by the player.

For smoke bomb, if they do nothing for the duration but keep their threat, I would argue that it's acting as "normal" as possible from my end, and any improvement would involve changing behavior from the EBWizardry end to block sight instead of blocking AI.  I may ping EB once we've sorted out all the info so he can look this over too.

For mind trick, based on your comment, I'm still not 100% clear as to what it's doing...does the mob literally do nothing, or does the mob attack your enemies?  I think it does the latter without DS installed, but can't remember for sure.

**Comment by Jackiecrazy** [comment]
Smoke bomb applies blindness to mobs in the most recent update, so that's solved. Mind trick is supposed to render a mob neutral for the duration, and it does that well; it's just the HUD.

**Comment by Laike-Endaril** [comment]
I'll see if I can make it so that while under the affect of mind trick, an entity's activity shows as "confused" instead of eg. "attacking X".  This way, the entity's threat is still retained (as if it simply has no memories from the time period when it was "tricked", and therefore goes back to what it was doing before).

**Comment by Laike-Endaril** [comment]
Alright, the newest version of DS should support the mind trick and mind control spells properly.  I referenced their descriptions on EB's github...wiki...thing to decide how to treat them.

Mind trick disables all targeting and all threat generation

Mind control...is more complex to explain, but seems to be working correctly now.  Notably, you cannot assassinate an entity under your own mind control.

Hmm...at some point, I may need to widen the scope of that to include entities on your team...didn't test that.

Feel free to post here if there's any follow-up, and I'll reopen if needed
