### ISSUE TITLE
additional stealth effect

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Dynamic-Stealth#9]
Hi this is a suggestion rather than a bug report,

I know one of the suggested mods to use with this is backstab (which unfortunately isn't viable for me as it currently doesn't work on servers) but I don't think it really quite hits the mark as far stealth abilities go. 

Would it possible to do something like a damage bonus if you attack from stealth? 
Or maybe a configurable potion effect that you gain when undetected by hostile entities?

**Comment by Laike-Endaril** [comment]
Hmm, configurable stealth buffs sound interesting...

I'm going to leave this open for now and add it to my TODO list.  Very high chance of this being a thing in the future.

**Comment by Laike-Endaril** [comment]
I've been looking into this lately.  There are two major triggers I can think of right now:

1. Global stealth buffs
Always active so long as you're undetected by ALL entities, or at least all entities matching certain criteria.  The effects given could be pretty flexible, but the hard part is defining the circumstances under which the effect is given.  DS has no way of detecting a mob as "hostile"; only as "passive" or "non-passive".  Detecting whether a mob is hostile is far more difficult when other mods are taken into account, due to internal team/faction systems and other conditional hostility.

2. Event-driven stealth buffs
Buffs that do something when a certain forge event fires, the most likely one being when something is about to receive damage.  These are easy to define the criteria for, but maybe a little less flexible on the effects that can be given.  That being said, I think these are the better way to go overall.

I will probably be going with the 2nd method, with config looking something like this:

stealth buffs
    attack from stealth
        auto-crit (true/false)
        damage multiplier
        damage bonus (additive)
        potion effects given (after damage is dealt)
    kill from stealth
        potion effects given


Tell me your thoughts if you see this

**Comment by Laike-Endaril** [comment]
(anyone else interested in this may feel free to post their thoughts as well)

**Comment by Laike-Endaril** [comment]
Not sure why github thought I referenced this in those 2 issues...I never did.  Anyway, this is being actively worked on right now and will be part of the next released version (046)

**Comment by Laike-Endaril** [comment]
@MaskedBird This is now a thing in the latest release (046)

**Comment by ghost** [comment]
Hey, just wanted to follow up that I've been away from minecraft for a bit so I completely forgot about this. Thanks for adding it! I'll take a look and give some feedback when I can
