### ISSUE TITLE
CTD vanilla fix is blaming dynamic stealth

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Dynamic-Stealth#97]
[https://pastebin.com/q2fzq91p](url)

[https://pastebin.com/8cJMwEn3](url)

**Comment by Laike-Endaril** [comment]
VanillaFix is very likely stopping a *different* crash from happening, and in doing so, causing this one.

(Which happens very often btw; the server team I'm working on is using VanillaFix and I almost always need to scrape the full log rather than the crash log due to it)

**Comment by ghost** [comment]
Oki ive managed to figure out what was happening

A mod called Nyx spawns the occasional invisible mob and this is what is causing Dynamic stealth to CTD

**Comment by Laike-Endaril** [comment]
That still sounds odd, but I'll take a look at the Nyx mod

**Comment by Laike-Endaril** [comment]
I've been unable to reproduce the issue with just Nyx and Dynamic Stealth so far (using forced events via Nyx commands).

The only thing I see in Nyx's source code that would make an entity "invisible" is a special entity renderer, and I specifically tested against falling stars which use it.

Dynamic Stealth is compatible with the vanilla invisibility potion effect as well, ofc.

I'm not sure how you decided Nyx was involved, but I'm not sure it is.  If the crash happens again, please post the full log file instead of the crash report, and maybe I can figure out what's going on. 
 If the crash happened the last time you ran the game, then the file will be "latest.log" in the logs folder.
